services:
  clinic_history_ms:
    container_name: clinic_history_ms
    build:
      context: docker/clinic_history_ms
      dockerfile: Dockerfile
    image: 'clinic_history_ms:latest'
    ports:
      - '27017'